name: algoquest-services

services:
  postgres:
    container_name: algoquest-services-postgres
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: algoquest_services_db
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
